modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="create_bic_bit"
version="0.0.50"
displayName="Create Bicycles and Bitterballen"
displayURL="https://github.com/pyzpre/Create-Bicycles-Bitterballen"
logoFile="logo.png"
authors="Pyzpre, VoidMage"
description="G E K O L O N I S E E R D"

[[dependencies.create_bic_bit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.create_bic_bit]]
    modId="forge"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.create_bic_bit]]
    modId="flywheel"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_bic_bit]]
modId="create"
mandatory=true
versionRange="[0.5.1.e,)"
ordering="NONE"
side="BOTH"




